### ISSUE TITLE
Als procesteam willen we een sessie organiseren rondom de afhandeling van een reservering

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#29]
Beschrijving van de taken:
- [x] Organiseren van een sessie over de afhandeling van een reservering. 
- [x] Ter voorbereiding hierop een concept BPMN proces maken van het afhandelproces.
- [ ] N.a.v. de sessie een (voorlopig) definitieve versie van het afhandelproces maken + aan product owner aangeven wat in de MVP hiervan zou moeten zitten. 

Let op:
- [x] duidelijke beschrijving wat moet gebeuren
- [x] gekoppeld aan personen (assign)

**Comment by JanWillemKooi** [comment]
Wie moeten bij deze sessie aanwezig zijn? Op welke termijn is de sessie nodig?

**Comment by MichelleDautzenberg** [comment]
De sessie is nu ingepland op 6 november in Utrecht. 
Aanwezig: Patrick, Rick, Daphne, Michelle, Elena (inhoud Utrecht), en...

**Comment by JanWillemKooi** [comment]
@MichelleDautzenberg en @DdeBruijn Gaan jullie morgen iets vertellen over de uitkomsten?

**Comment by MichelleDautzenberg** [comment]
Sessie heeft plaatsgevonden.
