### ISSUE TITLE
Als procesteam wil ik bij de business checken of de ontwikkelde checks afdoende zijn en op welk moment ze moeten plaatsvinden

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#30]
Controle partners en getuigen obv BRP gebeurt automatisch met de ontwikkelde checkservices (bij Melding én bij inloggen met Digid). We moeten nog checken of:
- dit inderdaad inhoudelijk de lading dekt voor de business.
- bepalen waar in het proces welke checks moeten worden uitgevoerd (vastleggen in DMN)
- eventuele te verwachten uitzonderingen in kaart brengen. 

Let op:
- [ ] duidelijke beschrijving wat moet gebeuren
- [x] gekoppeld aan een persoon (assign)
- [ ]  gekoppeld aan een user story (door # en het nummer toe te voegen)

**Comment by MichelleDautzenberg** [comment]
Checks zijn afdoende.
Komt ook terug in #52
