### ISSUE TITLE
Als burger wil ik weten wat de betekenis is van de kleuren bij de datumpikker

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#300]
zodat ik een nog betere ervaring met de huwelijksplanner heb

- [x] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [x] Koppel de juiste labels
- [x] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

Voorstel om een korte legenda voor blauwe en rode data te geven

![afbeelding](https://user-images.githubusercontent.com/45660740/72977049-f077d380-3dd3-11ea-948e-0ea71a78adfc.png)

**Comment by rubenvdlinde** [comment]
Defacto gaat het hier dan om een leganda
