### ISSUE TITLE
Als medewerker wil ik de agenda van de Babsen kunnen inzien en bewerken (Scherm)

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#340]
zodat we een correcte beschikaarheid kunnen invoeren

Acties:
- Overzicht van agenda's
- Agenda's kunnen bewerken
- opdelen is agenda inzien en reserveren/ blokkeren
- Voor uitvoering, zie #339
- Zie ook #51 

- [x] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [x] Koppel de juiste labels
- [x] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [x] Voeg alle taken die nodig zijn voor de user story toe.

DoD
Als de agenda overzichtelijk is, overzicht van week, maand, jaar.
Tijdsloten kunnen bewerken/ reserveren

**Comment by rubenvdlinde** [comment]
Dubbel met #339 339

**Comment by MichelleDautzenberg** [comment]
Voor eerste scherm akkoord.
