### ISSUE TITLE
Als medewerker wil ik een overzicht van alle binnengekomen meldingen

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/huwelijksplanner#346]
zodat ik de status kan inzien en er actie op kan nemen.

- [X] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [X] Koppel de juiste labels
- [X] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [X] Voeg alle taken die nodig zijn voor de user story toe.

- overzicht van alle binnengekomen meldingen
- status van behandeling zoals goedgekeurd, in behandeling , afgewezen of ontvangen

DoD
- Overzicht van de meldingen met status van behandeling kunnen zien en er actie op kunnen ondernemen.

Zie ook #161, #160, #54 

De volgende dingen moeten goed gekeurd kunnen worden:
- oudergegevens, (punt ouders)
- locatie huwelijk,
- datum
- Babs
- leeftijd
- naamgebruik
- curatele
- check tolk nodig?
- schijnhuwelijkverklaring
- verblijfstitel, zodat er een automatische controle komt wat nu uit Key2 wordt gehaald en alles klopt.

**Comment by rubenvdlinde** [comment]
@bbrands02 zou je los van het scherm overzicht huwelijks dossier ook een scherm controle melding kunnen maken aan de hand van de bovenstaande criteria.
