### ISSUE TITLE
Als inwoner wil bij naamgebruik de opties op mijn situatie worden toegepast

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#427]
zodat het duidelijker is wat mijn opties zijn. 

Dus opties aanpassen naar:

- [ ] Anita Henrika de Kieft
- [ ] Anita Henrika De Kieft - Dekker
- [ ] Anita Henrika Dekker - de Kieft
- [ ] Anita Henrika Dekker

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
Mapping velden formulier op OpenZaak:

Eigenschap 1) naamgebruikPartner1
Eigenschap 2) naamgebruikPartner2

**Comment by matthiasoliveiro** [comment]
Geblokkeerd door 601
