### ISSUE TITLE
Als developer wil ik een design voor de frontend van de Melding voorgenomen huwelijk

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#429]
zodat ik deze snel kan ontwikkelen. 

Hoort bij EPIC #86 

- [x] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [x] Koppel de juiste labels
- [x] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [x] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by JeroenduC** [comment]
Wireframe. De nummers in het roze corresponderen met hieronder beschreven teksten:

![20200227_130100](https://user-images.githubusercontent.com/49227194/75444037-ed3bae80-5962-11ea-9bcc-faf1e7279eeb.jpg)

(1) Goed om te weten: alles op deze pagina over trouwen/huwelijk, geldt ook voor geregistreerd partnerschap.

(2) Om te trouwen of uw partnerschap te registreren, moet u eerst uw voorgenomen huwelijk melden (vroeger ‘ondertrouw’ genoemd). U doet dit bij de gemeente waar u wilt trouwen. Tussen de melding en het huwelijk moet minimaal 14 dagen en mag maximaal 1 jaar zitten. Zorg dus dat u uw huwelijk ruim op tijd meldt.

(3) Is de melding van uw voorgenomen huwelijk in orde, dan ontvangt u van ons per mail een bericht. Is de online melding niet volledig? Dan nemen wij contact met u op. We vertellen u dan wat u nog moet doen.

(4) Er zijn een aantal voorwaarden waar u en uw partner aan moeten voldoen om een Melding Voorgenomen Huwelijk goed te laten keuren. Door u melding te doen verklaart u het volgende:

// Hieronder staan een set aan checkboxjes. De (i) zou een extra-informatie tekentjes moeten zijn waar men op klikt om extra informatie te krijgen. Klik in plaats van mouse-over omdat er linkjes in staan.

[] Ik en/of mijn partner wonen minimaal een half jaar in Nederland. 
(i) Om de melding te kunnen doen moeten u en uw partner allebei minstens een half jaar in Nederland wonen. Als u geen van beiden in Nederland woont, dan moet u uw huwelijk aankondigen in Den Haag. Meer informatie vindt u op de website van Den Haag, melding doen van huwelijk voor Nederlanders die in het buitenland wonen.
Let op: vanuit het buitenland duurt het vaak langer om de juiste documenten aan te leveren en om uw huwelijk vast te leggen en te betalen. Begin daarom op tijd.

[] Ik verklaar dat ik en mijn partner allebei 18 jaar of ouder zijn op het moment van trouwen of registreren partnerschap. 

[] Ik verklaar niet al getrouwd te zijn of een geregistreerd partnerschap te hebben. 
(i)Als u uw geregistreerd partnerschap om wil laten zetten naar een huwelijk dan heeft u natuurlijk wel al een geregistreerd partnerschap. 

[] Ik verklaar geen directe familie te zijn van mijn partner. 
(i) Dus geen broer/zus, ouder/kind of grootouder/kleinkind.

[] Ik verklaar dat ik niet trouw om een verblijfsvergunning te verkrijgen. 
(i) Hebt u of uw partner een nationaliteit van een land buiten de Europese Unie (EU/EER) en een verblijfsvergunning voor bepaalde tijd (dit staat op de voorkant van uw verblijfspasje)? Dan moet u allebei de verklaring schijnhuwelijk bij de melding voorgenomen huwelijk afleggen.
Hiermee verklaart u dat u niet trouwt om een verblijfsvergunning te krijgen. Vermoeden wij dat er toch sprake is van een schijnhuwelijk, dan stellen wij een onderzoek in. Zijn wij hierna overtuigd dat er mogelijk sprake is van een schijnhuwelijk, dan weigert de gemeente aan de huwelijksvoltrekking of het geregistreerd partnerschap mee te werken. De eigen verklaring blijft bewaard voor de Immigratie- en Naturalisatiedienst (IND).

[] Ik verklaar dat ik of mijn partner niet onder curatele staan. 
(i)Als u onder curatele gesteld bent dan heeft u toestemming nodig van uw curator om goedkeuring te krijgen voor uw melding voorgenomen huwelijk.

(5) Button is inactive totdat alle vinkjes zijn aangevinkt.

(6) Kunt u niet aan één of meerder van bovenstaande eisen voldoen en wilt u toch uw melding voorgenomen huwelijk doen? Belt u dan met onze servicebalie: 14030.

**Comment by JeroenduC** [comment]
@MichelleDautzenberg : Ons gesprek is hierboven verder uitgewerkt.

**Comment by MichelleDautzenberg** [comment]
Top!
