### ISSUE TITLE
Als koppel wil ik samen 2 tot 4 getuigen kunnen vragen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#458]
Na uitvoering besproken te hebben bij meerdere gemeenten, zijn we tot de conclusie gekomen dat we dit onnodig moeilijk hebben geïmplementeerd. Daarom ook de vraag om het te versimpelen. 

Dat is anders dan hoe we het nu geïmplementeerd hebben, namelijk dat er een relatie tussen partner en getuige is.

Acties:

- [ ] Tekst aanpassen
- [ ] Lijstje met partners rechts verwijderen

![image](https://user-images.githubusercontent.com/48316239/76089175-7ed99a80-5fb9-11ea-95f1-9d98ac2d4964.png)

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by rubenvdlinde** [comment]
Volgensmij bevat dit gen grafische wijzigingen dus kunnen we die gewoon oppakken. Geld dit voor alle gemeenten of moeten we dit configureerbaar maken?

**Comment by MichelleDautzenberg** [comment]
Dit geldt voor alle gemeenten, dus hoeft niet configurabel te zijn. Mag inderdaad nu opgepakt worden.

**Comment by rjzondervan** [comment]
@rubenvdlinde Kan jij https://github.com/ConductionNL/huwelijksplanner-ui/pull/55 nog even bekijken/mergen? Dan kan dit de deploy in ;)

**Comment by MichelleDautzenberg** [comment]
Het zinsdeel 

> , minimaal 1 en maximaal 3 per partner

 mag er nog uit.
