### ISSUE TITLE
Als functioneel beheerder wil ik BPMN modellen voor zaakgerichte processen naar Camunda deployen

### ISSUE THREAD

**Issue by MichelleDautzenberg** [VNG-Realisatie/huwelijksplanner#531]
zodat we deze processen zaakgericht af kan handelen mbv Camunda en OpenZaak.

- [ ] Naamgebruik
- [ ] Eigen locatie
- [ ] Melding
- [ ] Eigen Babs (reeds beëdigd)
- [ ] Eigen Babs (nog niet beëdigd)

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [ ] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Voeg alle taken die nodig zijn voor de user story toe.

**Comment by MichelleDautzenberg** [comment]
Ik denk dat er nog wat gewijzigd moet worden aan deze modellen, dus ik zet hem terug naar In Progress en op mijn naam.

**Comment by rubenvdlinde** [comment]
Stond nu alleen op mijn naam ;)
