### ISSUE TITLE
Als architect / developer wil ik weten welke hoe we de proceslaag in vullen

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#68]
zodat we dit op kunnen nemen in de architectuur en kunnen gebruiken als basis voor verdere ontwikkelingen

- [ ] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [x] Koppel de juiste labels
- [ ] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [ ] Let er op dat de user story in 1 sprint gerealiseerd kan worden

Gerelateerd aan #66

**Comment by matthiasoliveiro** [comment]
Als developer heb ik de verwachting dat we een oplossingsrichting hebben gekozen aan het einde van deze story.

**Comment by matthiasoliveiro** [comment]
@CMasselink gaat een nieuwe meeting in te plannen.

**Comment by rubenvdlinde** [comment]
Kan @matthiasoliveiro dit user story opsplitsen

**Comment by matthiasoliveiro** [comment]
De proces meeting ging over het landschap, maw deze vraag staat nog open en is terug naar todo

**Comment by JanWillemKooi** [comment]
Gisteren heb ik met Kunera gesproken. Ik ga er vanuit dat deze vraag gaat over laag 4 en het toepassen van Camunda of de Eindhoven variant. Net met @CMasselink gesproken. We proberen hier morgenmiddag (18 dec) 13:00-14:30 een klap op te geven.

**Comment by matthiasoliveiro** [comment]
Na aanleiding van de meeting op 9 januari. Er is een onderzoek gaande naar dit onderwerp en eind januari verwachten we hier een advies in. Na aanleiding van dit advies zal er een beslissing worden genomen op dit onderwerp. (issue staat onhold tot dat het advies is geleverd)

**Comment by matthiasoliveiro** [comment]
Na aanleiding van de designweek  het volgende besloten: 
Camunda niet in de MVP want te groot van omvang.
NLDesign system mogelijk wel onderzoek nodig!

(issue oppakken sprint 8)

**Comment by CMasselink** [comment]
Zie design decisions.
