### ISSUE TITLE
EPIC: Als koppel wil ik via de trouwplanner mijn melding voorgenomen huwelijk kunnen doen

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#86]
zodat we daar niet weer een aparte website voor hoeven te gebruiken / alles van ons huwelijk vanuit 1 omgeving kunnen regelen

**Toelichting**
In deze userstory beschrijven we alles wat gedaan moet worden in de huwelijksplanner om de melding voorgenomen huwelijk van indienen tot en met afhandeling te kunnen ondersteunen.

- [x] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [x] Koppel de juiste labels
- [x] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [x] Voeg alle taken die nodig zijn voor de user story toe.

**Acties**
- [ ] User interactie frontend (klant) opstellen (inclusief berichten/notificaties) o.a. #429 #441 
- [ ] User interactie frontend (medewerker) opstellen #640 #476 
- [x] Beschrijven welke gegevens in de melding moeten komen (zie zaaktypen.md)
- [ ] Zaak maken voor melding voorgenomen huwelijk #482 #527 
- [ ] Bepalen hoe medewerker melding wil afhandelen #482 #476 
- [ ] Inrichten van melding behandel functionaliteit #482

**Comment by rubenvdlinde** [comment]
Afhankelijk van wat @MichelleDautzenberg onder #38 geconcludeerd heeft is het merendeel van de data denk ik aanwezig.

Zowel zaak,verzoek als berichten API's zijn inmiddels tot onze beschikking. Dus als we dit verhaal goed kunnen uitwerken lijkt het mij (gezien de prio) een mooie voor de design week.

**Comment by rubenvdlinde** [comment]
Oke, na afgelopen design week en vandaag zou dit gewoon mogelijk moeten zijn. @rjzondervan zou jij eens kunnen kijken of we nog technisch dingen missen? En zo ja of het ook visueel al binnen de hpui kan?

**Comment by matthiasoliveiro** [comment]
Jeroen en Renee gaan een voorbeeld maken (instelling is om dit mee te nemen op stap 0) @JeroenduC

**Comment by MichelleDautzenberg** [comment]
Onderstaande met Kunera en Constantijn afgesproken:

@JeroenduC Willen jullie in de design schetsen voor de melding ook meenemen: 
- verklaringen afleggen van niet onder dwang/curatele, reeds getrouwd in het buitenland en geen verwantschap

**Comment by CMasselink** [comment]
We hebben deze userstory gewijzigd in een EPIC. Wordt nog verder gesliced.

**Comment by JeroenduC** [comment]
Bij deze de wireframe met toevoegingen:
![20200220_165114](https://user-images.githubusercontent.com/49227194/74953076-79008880-5401-11ea-8636-c0d988afb1e5.jpg)

De roze nummers zijn wat extra opmerkingen, zie hieronder:

(1)	 Goed om te weten: alles op deze pagina over trouwen/huwelijk, geldt ook voor geregistreerd partnerschap. 

(2)	Om te trouwen of uw partnerschap te registreren, moet u eerst uw voorgenomen huwelijk melden (vroeger ‘ondertrouw’ genoemd). U doet dit bij de gemeente waar u wilt trouwen. Tussen de melding en het huwelijk moet minimaal 14 dagen en mag maximaal 1 jaar zitten. Zorg dus dat u uw huwelijk ruim op tijd meldt.

(3)	Is de melding van uw voorgenomen huwelijk in orde, dan ontvangt u van ons per mail een bericht. Is de online melding niet volledig? Dan nemen wij contact met u op. We vertellen u dan wat u nog moet doen. 

(4)	[Dropdown titel]
Er zijn een aantal voorwaarden waar u en uw partner aan moeten voldoen om een Melding Voorgenomen Huwelijk goed te laten keuren. 

[Dropdown inhoud]

•	U en uw partner wonen allebei minstens een half jaar in Nederland.
Als u geen van beiden in Nederland woont, dan moet u uw huwelijk aankondigen in Den Haag. Meer informatie vindt u op de website van Den Haag, [melding doen van huwelijk voor Nederlanders die in het buitenland wonen](https://www.denhaag.nl/nl/trouwen-en-geregistreerd-partnerschap/huwelijk/huwelijk-en-partnerschap-voor-nederlanders-die-in-het-buitenland-wonen-melden.htm). 
Let op: vanuit het buitenland duurt het vaak langer om de juiste documenten aan te leveren en om uw huwelijk vast te leggen en te betalen. Begin daarom op tijd. 
•	U trouwt in de gemeente Utrecht.
•	U bent allebei niet getrouwd.
•	U heeft geen geregistreerd partnerschap (behalve met elkaar). 
•	U bent allebei 18 jaar of ouder op de trouwdatum.
•	U bent geen directe familie van elkaar. Dus geen broer/zus, ouder/kind of grootouder/kleinkind.
•	Als u onder curatele gesteld bent dan heeft u toestemming nodig van uw curator om goedkeuring te krijgen voor uw melding voorgenomen huwelijk. 
•	Informatie over bijvoorbeeld uw ouders en eventuele eerdere huwelijken zijn in de basisregistratie persoonsgegevens (BRP) bij uw gegevens geregistreerd. 
Dit kunt u controleren op [MijnOverheid.nl](MijnOverheid.nl). Log in met uw DigiD en bekijk deze informatie via ‘Persoonlijke gegevens’, ‘Basisregistratie Personen’ en ‘Familie’. Ontbreken er gegevens over uw ouders of eerdere huwelijk(en)? Neem dan contact met ons op via telefoonnummer 14 030.
•	Hebt u of uw partner een nationaliteit van een land buiten de [Europese Unie (EU/EER)](https://www.rijksoverheid.nl/onderwerpen/europese-unie/vraag-en-antwoord/welke-landen-horen-bij-de-europese-economische-ruimte-eer)  en een verblijfsvergunning voor bepaalde tijd (dit staat op de voorkant van uw verblijfspasje)? Dan moet u allebei de [verklaring schijnhuwelijk](https://www.rijksoverheid.nl/onderwerpen/immigratie/inhoud/schijnhuwelijk-voorkomen) bij de melding voorgenomen huwelijk afleggen.
Hiermee verklaart u dat u niet trouwt om een verblijfsvergunning te krijgen. Vermoeden wij dat er toch sprake is van een schijnhuwelijk, dan stellen wij een onderzoek in. Zijn wij hierna overtuigd dat er mogelijk sprake is van een schijnhuwelijk, dan weigert de gemeente aan de huwelijksvoltrekking of het geregistreerd partnerschap mee te werken. De eigen verklaring blijft bewaard voor de Immigratie- en Naturalisatiedienst (IND).

(5) [Doe Melding]

**Comment by JeroenduC** [comment]
Voor punt 4 nog even wat extra toelichting: 
![image](https://user-images.githubusercontent.com/49227194/75024885-8158d200-549a-11ea-84d5-3d83558fa78e.png)

**Comment by JeroenduC** [comment]
Na een gesprek met Michelle tot wat extra inzichten gekomen over de voorwaarden. Er is een aangepaste wireframe en aangepaste tekst. 

Omdat er een apart issue is aangemaakt voor de frontend heb ik de nieuwe informatie in #429 gezet.

**Comment by JeroenduC** [comment]
Verder uitgewerkt in #429

**Comment by MichelleDautzenberg** [comment]
Na nader onderzoek is gebleken dat de getuigen niet bekend hoeven te zijn bij de melding.
Ik heb [hier ](https://github.com/VNG-Realisatie/huwelijksplanner/blob/master/documenten/MVH%2C%20standaard.doc) een document gezet waarin de minimale vragen staan die we moeten stellen bij een melding voorgenomen huwelijk. We mogen antwoorden daarin voorinvullen, maar ze moeten allemaal inzichtelijk zijn voor de inwoner voordat hij/zij de melding indient!

**Comment by CMasselink** [comment]
Actiepunt: kijken of we voor alle acties in de initiele beschrijving userstory's hebben. Daarna kan deze dicht.

**Comment by MichelleDautzenberg** [comment]
Gecheckt en alles userstories zijn er.
