### ISSUE TITLE
Als klant wil ik de kosten voor het huwelijk online kunnen betalen

### ISSUE THREAD

**Issue by CMasselink** [VNG-Realisatie/huwelijksplanner#93]
zodat ik niet langs de balie hoef te komen om te betalen

**Voorgestelde oplossingsrichting**
Ideal als betaaloptie bieden voor de klant.
Ingenico als eerste payment provider

- [x] Zorg dat de beschrijving duidelijk voor iedereen in het team is
- [x] Koppel de juiste labels
- [x] Koppel eventueel aan een epic (door # en het nummer toe te voegen)
- [x] Voeg alle taken die nodig zijn voor de user story toe.

**Acties**
- [x] Bepalen welke payment provider er gebruikt gaat worden
- [ ] Uitzoeken wat er technisch nodig is om aan te sluiten op de gekozen payment provider
- [ ] Technisch realiseren aansluitmogelijkheid voor payment provider 

**Optioneel**
- [ ] Bepalen of we extra betaalopties toestaan/implementeren als de payment provider deze aanbiedt.

**Comment by CMasselink** [comment]
Gerelateerd aan #64

**Comment by CMasselink** [comment]
Moet alleen nog ingeschat worden.

**Comment by rubenvdlinde** [comment]
Hangt ook goed samen met andere ontwikkelingen van de afgelopen week.

Hebben we een test acount voor de betaal provider van Utrecht?

**Comment by CMasselink** [comment]
We hebben op dit moment nog geen testaccount voor de betaalprovider die Hoorn, Utrecht en Almere gebruiken. Voorlopig gebruiken we voor testdoeleinden Molly

**Comment by rubenvdlinde** [comment]
Mollie ;)

@rjzondervan dat betekend dat we dus ook even de Conduction test mollie sleutel kunnen gebruiken.

**Comment by rjzondervan** [comment]
Inmiddels is de mogelijkheid om te betalen toegevoegd op de devomgeving.

**Comment by CMasselink** [comment]
Technisch akkoord bevonden. De meldingen kunnen nog wel wat scherper.

**Comment by CMasselink** [comment]
Werkt op demo
